import "./globals.css";
import "ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./NextAuthProvider";
import { RecoilProvider } from "./Recoilprovider";
import { ClientProvider } from "./ClientProviders";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
            <ClientProvider >
               {children}
            </ClientProvider>
      </body>
    </html>
  );
}
